### PR TITLE
Issue - 42 WhisperKit support simulator fixed

### LINKED ISSUE #42: Does WhisperKit support simulator? It emits only [silence] on Simulator but on-device is good.

### PR DESCRIPTION
**Pull request by bharat9806**
#42

### CODE REVIEW

File: Sources/WhisperKit/Core/Models.swift [hunk 1]
```diff
@@ -129,7 +129,7 @@ public struct ModelComputeOptions {
     public var prefillCompute: MLComputeUnits
 
     public init(
-        melCompute: MLComputeUnits = .cpuAndGPU,
+        melCompute: MLComputeUnits = .cpuOnly,
         audioEncoderCompute: MLComputeUnits = .cpuAndNeuralEngine,
         textDecoderCompute: MLComputeUnits = .cpuAndNeuralEngine,
         prefillCompute: MLComputeUnits = .cpuOnly
```
Comment (ZachNagengast) [inline Sources/WhisperKit/Core/Models.swift:135]:
```suggestion
        #if targetEnvironment(simulator)
        melCompute: MLComputeUnits = .cpuOnly,
        audioEncoderCompute: MLComputeUnits = .cpuOnly,
        textDecoderCompute: MLComputeUnits = .cpuOnly,
        prefillCompute: MLComputeUnits = .cpuOnly
        #else
        melCompute: MLComputeUnits = .cpuAndGpu,
        audioEncoderCompute: MLComputeUnits = .cpuAndNeuralEngine,
        textDecoderCompute: MLComputeUnits = .cpuAndNeuralEngine,
        prefillCompute: MLComputeUnits = .cpuOnly
        #endif        
```

**Review by ZachNagengast — CHANGES_REQUESTED** [review]
Yep like @muukii mentioned, we'll want this to be default only for the simulator - see comment suggestion

Here's another example of how it should work https://github.com/huggingface/swift-transformers/pull/46/files

**Comment by ZachNagengast** [comment]
@bharat9806 based on this issue https://github.com/argmaxinc/WhisperKit/issues/65 I'd also like to push a fix to this branch and bundle them together, the tests are currently failing - will want to merge with main as well

**Review by ZachNagengast — APPROVED** [review]
